### ISSUE TITLE
MySQL JSON column type throws error.

### ISSUE THREAD

**Issue by tankerkiller125** [rexxars/sql-to-graphql#42]
```
{ tableName: 'recipes',
  columnName: 'ingredients',
  ordinalPosition: 5,
  isNullable: 'NO',
  dataType: 'json',
  columnKey: '',
  columnType: 'json',
  columnComment: '' }
Unhandled rejection Error: Type "json" not recognized
    at getType (/usr/lib/node_modules/sql-to-graphql/steps/column-to-object.js:127:19)
    at columnToObject (/usr/lib/node_modules/sql-to-graphql/steps/column-to-object.js:16:8)
    at /usr/lib/node_modules/sql-to-graphql/steps/table-to-object.js:16:16
    at Array.map (native)
    at Object.tableToObject (/usr/lib/node_modules/sql-to-graphql/steps/table-to-object.js:15:32)
    at onTableDataCollected (/usr/lib/node_modules/sql-to-graphql/cli.js:127:23)
    at /usr/lib/node_modules/sql-to-graphql/node_modules/async/lib/async.js:726:13
    at /usr/lib/node_modules/sql-to-graphql/node_modules/async/lib/async.js:52:16
    at done (/usr/lib/node_modules/sql-to-graphql/node_modules/async/lib/async.js:246:17)
    at /usr/lib/node_modules/sql-to-graphql/node_modules/async/lib/async.js:44:16
    at /usr/lib/node_modules/sql-to-graphql/node_modules/async/lib/async.js:723:17
    at /usr/lib/node_modules/sql-to-graphql/node_modules/async/lib/async.js:167:37
    at /usr/lib/node_modules/sql-to-graphql/node_modules/async/lib/async.js:726:13
    at /usr/lib/node_modules/sql-to-graphql/node_modules/async/lib/async.js:52:16
    at done (/usr/lib/node_modules/sql-to-graphql/node_modules/async/lib/async.js:246:17)
    at /usr/lib/node_modules/sql-to-graphql/node_modules/async/lib/async.js:44:16
```

**Comment by rexxars** [comment]
Unsure what we can do about JSON types, to be honest. If I understand correctly, JSON fields doesn't have any schema, and thus representing them in a strict API such as GraphQL .

**Comment by tankerkiller125** [comment]
My way of doing it for now is that I converted it to a standard text type. And then I just have GraphQL return the entire JSON statement. Allowing the client to handle the JSON itself.
